spring:
  application:
    name: naraka-cloud-rule
  cloud:
    nacos:
      config:
        refresh-enabled: true
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        timeout: 3001
      discovery:
        enabled: true
        server-addr: localhost:8848
  config:
    import:
      - nacos:naraka-cloud-rule.yaml
  mvc:
    servlet:
      path: /rule
