logging:
  level:
    root: debug
spring:
  application:
    name: naraka-cloud-rule
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/puppeteer
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
naraka:
  security:
    enable: true
  encrypt:
    enable: true
    keyMap:
      phone: dsadas$#@$@#
  jackson:
    objectMapper: true
    messageConverter: true
    deserializerSmart: true
  username:
    header: username
  jpa:
    typeEnumsPackage: com.davies.naraka.rule.domain.enums