logging:
  level:
    root: debug
spring:
  application:
    name: naraka-cloud-puppeteer
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:./mydb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

naraka:
  security:
    enable: true
  encrypt:
    enable: true
    keyMap:
      phone: dsadas$#@$@#
  jackson:
    objectMapper: true
    messageConverter: true
    deserializerSmart: true

  username:
    header: username
  jpa:
    typeEnumsPackage: com.davies.naraka.puppeteer.domain.enums