logging:
  level:
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  application:
    name: naraka-cloud-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: auth-center
          uri: lb://naraka-cloud-admin
          predicates:
            - Path=/admin/**
            - Token=useranme
          filters:
            - AddRequestHeader=useranme, {useranme}
    sentinel:
      transport:
        dashboard: localhost:8089
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
naraka:
  security:
    jackson: false
    enable: true
    remoteUser: false
jwt:
  token:
    serviceIssuer: service
