logging:
  level:
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  config:
    import:
      - nacos:naraka-cloud-gateway.yaml
  application:
    name: naraka-cloud-gateway
  cloud:
    nacos:
      discovery:
        enabled: true
      config:
        refresh-enabled: true
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        timeout: 3001

naraka:
  security:
    enable: true

