logging:
  level:
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  application:
    name: naraka-cloud-gateway
  cloud:
    nacos:
      config:
        refresh-enabled: true
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        timeout: 3001
  config:
    import:
      - nacos:naraka-cloud-gateway.yaml
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: auth-center
          uri: lb://naraka-cloud-admin
          predicates:
            - Path=/admin/**
            - Token=useranme
          filters:
            - AddRequestHeader=useranme, {useranme}
    sentinel:
      transport:
        dashboard: localhost:8089
naraka:
  security:
    enable: true

