logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: naraka-cloud-admin
  cloud:
    nacos:
      config:
        refresh-enabled: true
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        timeout: 3001
      discovery:
        enabled: true
        server-addr: localhost:8848
