logging:
  level:
    root: debug
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/naraka
    username: root
    password: 12345678
app:
  data:
    encrypt:
      defaultKey: 3DA@231$%aswsdas
      keyMap:
        phone: dsadas$#@$@#

mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.davies.naraka.admin.domain.enums;com.davies.naraka.cloud.common.enums
naraka:
  redis:
    address: redis://127.0.0.1:6379
  security:
    enable: true
  jackson: true
  username:
    header: username