logging:
  level:
    root: debug
spring:
  application:
    name: naraka-cloud-admin
  cloud:
    nacos:
      config:
        refresh-enabled: true
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        timeout: 3001
  config:
    import:
      - nacos:naraka-cloud-admin.yaml
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/naraka
    username: root
    password: 12345678


mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.davies.naraka.admin.domain.enums;com.davies.naraka.cloud.common.enums
naraka:
  encrypt:
    defaultKey: 3DA@231$%aswsdas
    keyMap:
      phone: dsadas$#@$@#
    enable: true
  redis:
    address: redis://127.0.0.1:6379
  security:
    enable: true
  jackson:
    messageConverter: true
    smartConverter: true
  username:
    header: username